export interface StudentCVData {
    id: string,
    email: string,
    tel: number,
    firstName: string,
    lastName: string,
    githubUsername: string,
    portfolioUrls: string[],
    projectUrls: string[],
    bio: string,
    expectedTypeWork: string,
    targetWorkCity: string,
    expectedContractTpe: string,
    expectedSalary: string,
    canTakeApprenticeship: boolean,
    monthsOfCommercialExp: number,
    education: string,
    workExperience: string,
    courses: string,
}